
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 26 00:06:54 CST 2017
//----------------------------------------------------

package projectf;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int saltodelinea = 11;
  public static final int CONJ = 8;
  public static final int hasta = 24;
  public static final int com = 13;
  public static final int coma = 18;
  public static final int identificador = 32;
  public static final int seguido = 19;
  public static final int iniciofin = 21;
  public static final int corcheteCerrado = 27;
  public static final int puntoycoma = 20;
  public static final int ytext = 5;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int ceroomas = 22;
  public static final int concat = 14;
  public static final int ceroouna = 16;
  public static final int barra = 3;
  public static final int rang = 35;
  public static final int unaomas = 15;
  public static final int res = 10;
  public static final int dospuntos = 25;
  public static final int comillasD = 30;
  public static final int tabulacion = 12;
  public static final int guionbajo = 17;
  public static final int corcheteAbierto = 26;
  public static final int orr = 23;
  public static final int eror = 2;
  public static final int comillaS = 34;
  public static final int parentesisC = 29;
  public static final int ycol = 7;
  public static final int parentesisA = 28;
  public static final int num = 31;
  public static final int retorno = 9;
  public static final int todo = 4;
  public static final int decimal = 33;
  public static final int yrow = 6;
}

